### ISSUE TITLE
How to do simple CIL? Not online

### ISSUE THREAD

**Issue by LightingMc** [eric11220/pretrained-models-in-CL#3]
Thanks for your awesome work. Is it possible to use this repo to do simple Class incremental learning CIL and not online CIL? 

https://github.com/eric11220/pretrained-models-in-CL/blob/master/experiment/run.py
        if params.online:
Seems to be related to whether we are doing the Two-stage Training.

I am wondering what if we have access to all of the dataset for a given task and can iteratively learn on till convergence before moving onto the next task?

**Comment by eric11220** [comment]
You should be able to do so by providing a different #epoch here.
https://github.com/eric11220/pretrained-models-in-CL/blob/master/general_main.py#L68-L69
